-- AlterEnum: add GARANTIA_EFECTIVO to ConceptoCaja
ALTER TABLE `MovimientoCaja` MODIFY COLUMN `concepto` ENUM('ANTICIPO_CONTRATO', 'PAGO_SALDO_CONTRATO', 'DEUDA_COBRADA', 'GARANTIA_EFECTIVO', 'DEVOLUCION_GARANTIA', 'GASTO_OPERATIVO', 'OTRO_INGRESO', 'OTRO_EGRESO') NOT NULL;
